# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b3cb74044e72f97e24f7280b8574e63ee3f7dd25562de4ae0e17d8d7431474f8c082d5217eac6d7ab4f90ed78748c5cb9d77e9ef8cb49ba9195493b72b36207

test:
  secret_key_base: 917cae9762d5ae7b01274fe74f71f93587bcbcf54c445869389e589728783bbbd27f0a833f2d507eed564e1964cd2815e51c433fa5baa12c00c137542014b2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
